baseurl = "/"
languageCode = "en-us"
title = "BILUMS"


[params]
  description = "String Bags in Papua New Guinea"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1


    
[[menu.main]]
    name = "E-Markets"
    url  = "/markets"
    weight = 4



[[menu.main]]
    name = "Blog"
    url  = "/blog"
    weight = 3


[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 2






    

    





