baseurl = "/"
languageCode = "en-us"
title = "BILUMS"
png = "Papua New Guinea"

[params]
  description = "APEC Challenge"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1


    
[[menu.main]]
    name = "Markets"
    url  = "/markets"
    weight = 4



[[menu.main]]
    name = "Blog"
    url  = "/blog"
    weight = 3


[[menu.main]]
    name = "Gallery"
    url  = "/gallery"
    weight = 2

[[menu.main]]
    name = "Maps"
    url  = "/maps"
    weight = 5


    

    





