backend:
  name: git-gateway
  branch : step-01-add-a-menu
  publish_mode: editorial_workflow
  

media_folder: "src/img/gallery" # Folder where user uploaded files should go

collections:    
  - name: markets
    label: "Markets SME" # Used in the UI, ie.: "New Post"
    folder: "site/content/markets" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Market", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string"} 

  - name: blog
    label: "Content" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Province", name: "origin", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Type Bilum,", name: "type", widget: "string"}
      - {label: "Price", name: "price", widget: "string"} 

  - name: gallery
    label: "Gallery Image" # Used in the UI, ie.: "New Post"
    folder: "site/content/gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"} 

    - name: maps
    label: "Maps" # Used in the UI, ie.: "New Post"
    folder: "site/content/maps" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Area Map", name: "image", widget: "image"}     
